import { describe, expect, test } from "bun:test"

describe("responsive bundle boundaries", () => {
  test("the entry shell lazy-loads both workspace implementations", async () => {
    const responsive = await Bun.file(new URL("./ResponsiveWorkspace.tsx", import.meta.url)).text()
    const app = await Bun.file(new URL("../App.tsx", import.meta.url)).text()
    expect(responsive).toContain('lazy(() => import("./desktop/DesktopWorkspace"))')
    expect(responsive).toContain('lazy(() => import("./mobile/MobileWorkspace"))')
    expect(responsive).toContain("<WorkspaceCommitSignal onReady={onReady} />")
    expect(responsive).toContain("useLayoutEffect(onReady, [onReady])")
    expect(app).not.toContain("MobileWorkspace")
    expect(app).not.toContain("DesktopWorkspace")
    expect(app).not.toContain('from "./components/Canvas"')
    expect(app).toContain("loaded && (!canOpenWorkspace || workspaceRendered)")
    expect(app).toContain("<ResponsiveWorkspace onReady={markWorkspaceRendered} />")
  })

  test("the install manifest includes separate standard and safely padded maskable icons", async () => {
    const manifest = await Bun.file(new URL("../../public/manifest.webmanifest", import.meta.url)).json() as { display: string; icons: Array<{ sizes: string; purpose: string; src: string }> }
    expect(manifest.display).toBe("standalone")
    expect(manifest.icons.filter((icon) => icon.purpose === "any").map((icon) => icon.sizes)).toEqual(["192x192", "512x512"])
    expect(manifest.icons.filter((icon) => icon.purpose === "maskable").map((icon) => icon.src)).toEqual(["/pwa-maskable-192.png", "/pwa-maskable-512.png"])

    const index = await Bun.file(new URL("../../index.html", import.meta.url)).text()
    expect(index).toContain("-webkit-tap-highlight-color: transparent")
    expect(index).toContain('input, textarea, [contenteditable="true"]')
  })

  test("mobile reuses the established canvas tabs and exposes tags through long press", async () => {
    const mobileTabs = await Bun.file(new URL("./mobile/MobileTabBar.tsx", import.meta.url)).text()
    const focusedTile = await Bun.file(new URL("./mobile/MobileFocusedTile.tsx", import.meta.url)).text()
    const workspace = await Bun.file(new URL("./mobile/MobileWorkspace.tsx", import.meta.url)).text()
    const overview = await Bun.file(new URL("./mobile/MobileOverview.tsx", import.meta.url)).text()
    const dragOverlay = await Bun.file(new URL("./mobile/MobileDragOverlay.tsx", import.meta.url)).text()
    const mobileTabBar = await Bun.file(new URL("./mobile/MobileTabBar.tsx", import.meta.url)).text()
    const tagMenu = await Bun.file(new URL("../components/TagMenu.tsx", import.meta.url)).text()
    const tabBar = await Bun.file(new URL("../components/TabBar.tsx", import.meta.url)).text()
    const spotlight = await Bun.file(new URL("../components/Spotlight.tsx", import.meta.url)).text()
    const history = await Bun.file(new URL("../components/HistoryPanel.tsx", import.meta.url)).text()
    const syncStatus = await Bun.file(new URL("../components/SyncStatusDot.tsx", import.meta.url)).text()
    const reauthentication = await Bun.file(new URL("../components/ReauthenticationOverlay.tsx", import.meta.url)).text()
    const app = await Bun.file(new URL("../App.tsx", import.meta.url)).text()
    const serviceWorkerRegistration = await Bun.file(new URL("../pwa/serviceWorker.tsx", import.meta.url)).text()
    const viteConfig = await Bun.file(new URL("../../vite.config.ts", import.meta.url)).text()

    expect(mobileTabs).toContain('import { TabBar } from "../../components/TabBar"')
    expect(mobileTabs).toContain("<TabBar")
    expect(focusedTile).toContain("beginTagLongPress")
    expect(focusedTile).toContain("mobileThoughtInsertionIndex")
    expect(focusedTile).toContain("targetIndex")
    expect(focusedTile).toContain("textRef.current")
    expect(focusedTile).toContain("onPointerDown={beginTextEditing}")
    expect(focusedTile).toContain("onFocusTarget(id, targetCanvasId)")
    expect(focusedTile).not.toContain("Thought options")
    expect(focusedTile).not.toContain("⋯")
    expect(overview).not.toContain('"Overview"')
    expect(workspace).not.toContain("previewCollapsed")
    expect(workspace).not.toContain("Hide canvas preview")
    expect(workspace).not.toContain("arranging")
    expect(workspace).not.toContain("MobileArrangeCanvas")
    expect(workspace).toContain("<MobileDragOverlay />")
    expect(workspace).toContain("<AiSparkleIcon")
    expect(workspace).toContain("window.requestAnimationFrame(draw)")
    expect(workspace).toContain("if (hasExpandedTextSelection()) return")
    expect(workspace).toContain("pointerEvent.pointerId !== pointerId")
    expect(workspace.match(/setMobileSplit\(/g)).toHaveLength(1)
    expect(workspace).not.toContain(">✦</")
    expect(dragOverlay).toContain("data-mobile-drag-preview")
    expect(dragOverlay).not.toContain("data-mobile-tile-lift-preview")
    expect(overview).toContain("HOLD_TO_DRAG_MS")
    expect(overview).toContain("HOLD_TO_DRAG_MS = 300")
    expect(overview).toContain("beginCrossCanvasDrag")
    expect(overview).toContain("moveCrossCanvasDrag(pointerEvent.clientX, pointerEvent.clientY)")
    expect(overview).toContain("suppressNativeSelection")
    expect(overview).toContain("setPointerCapture(event.pointerId)")
    expect(overview).toContain("<MobileUndoToast")
    expect(tabBar).toContain("subscribeCrossCanvasDragPointer")
    expect(overview).toContain("getMobileTileResize")
    expect(overview).toContain("data-mobile-tile-drag-preview")
    expect(overview).toContain("}, true)")
    expect(overview).toContain('aria-label="Add tile"')
    expect(mobileTabBar).not.toContain("Arrange canvas")
    expect(mobileTabBar).toContain("leftAccessory={null}")
    expect(overview).not.toContain("#f59e0b")
    expect(overview).toContain('draggingCanvas ? "#faf7ff" : "#f7f7f7"')
    expect(overview).toContain('border: "3px solid #7c3aed"')
    expect(overview).toContain("fontSize: 44")
    expect(history).toContain("buildHistoryFeed")
    expect(history).toContain('appearance="text"')
    expect(history).not.toContain("Sync activity")
    expect(syncStatus).toContain("<SavingSpinner fading />")
    expect(syncStatus).not.toContain("SyncDotVisual")
    expect(overview).not.toContain("translateZ(0)")
    expect(overview).not.toContain("willChange")
    expect(overview).toContain("overviewDragFeedback")
    expect(overview).toContain("canvasRef.current?.getBoundingClientRect()")
    expect(overview).toContain("boxSizing: \"border-box\"")
    expect(tabBar).toContain("disabled={Boolean(onOpenMenu)}")
    expect(tabBar).toContain("resolveTargetTap(lastTabTapRef.current, canvasIdentityKey(canvas)")
    expect(tabBar).not.toContain("onDoubleClick")
    expect(tagMenu).toContain("event.stopPropagation(); onClose()")
    expect(tagMenu).toContain("event.preventDefault(); event.stopPropagation()")
    expect(spotlight).toContain("All Canvases")
    expect(spotlight).toContain("cachedWorkspaceForSearch")
    expect(spotlight).toContain("readPastEntitiesCache")
    expect(spotlight).not.toContain("listPast()")
    expect(app).not.toContain("2500")
    expect(app).not.toContain("setInterval(syncNow")
    expect(app).toContain("void syncNow().catch(console.error)")
    expect(app).toContain("!isSignedIn && cachedUserId")
    expect(app).toContain("isLoaded && !isSignedIn && cachedUserId")
    expect(app).toContain("<ReauthenticationOverlay />")
    expect(reauthentication).toContain("Sign in again to continue")
    expect(reauthentication).toContain('aria-modal="true"')
    expect(workspace).not.toContain("identity not revalidated")
    expect(serviceWorkerRegistration).not.toContain("import.meta.env.DEV")
    expect(serviceWorkerRegistration).toContain("isCacheableClerkAsset")
    expect(viteConfig).toContain("configureServer(server)")
    expect(viteConfig).toContain("caches.match(cacheKey)")
    expect(viteConfig).toContain("/npm/@clerk/clerk-js@")
  })

  test("production desktop loading and PWA precaching exclude the mobile chunk", async () => {
    const manifest = await Bun.file(new URL("../../dist/.vite/manifest.json", import.meta.url)).json() as Record<string, { file: string; imports?: string[]; dynamicImports?: string[] }>
    const entry = manifest["index.html"]!
    const mobileKey = entry.dynamicImports?.find((key) => key.includes("MobileWorkspace"))
    const desktopKey = entry.dynamicImports?.find((key) => key.includes("DesktopWorkspace"))
    expect(mobileKey).toBeDefined()
    expect(desktopKey).toBeDefined()
    expect(entry.imports ?? []).not.toContain(mobileKey!)
    expect(manifest[desktopKey!]?.imports ?? []).not.toContain(mobileKey!)

    const serviceWorker = await Bun.file(new URL("../../dist/sw.js", import.meta.url)).text()
    const config = JSON.parse(serviceWorker.split("\n")[0]!.slice("const CONFIG = ".length, -1)) as { precache: string[]; workspaces: Record<string, string[]>; shell: string }
    expect(config.precache).not.toContain(`/${manifest[mobileKey!]!.file}`)
    expect(config.precache).not.toContain(`/${manifest[desktopKey!]!.file}`)
    expect(config.workspaces.mobile).toContain(`/${manifest[mobileKey!]!.file}`)
    expect(config.workspaces.desktop).toContain(`/${manifest[desktopKey!]!.file}`)
    expect(config.workspaces.desktop).not.toContain(`/${manifest[mobileKey!]!.file}`)
    expect(config.workspaces.mobile).not.toContain(`/${manifest[desktopKey!]!.file}`)
    expect(config.precache).toContain(config.shell)
    expect(serviceWorker).toContain("cache.match(SHELL)")
  })
})
